//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebStaff_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset_staff
    {
        public int asset_id { get; set; }
        public string desc_asset { get; set; }
        public Nullable<int> fk_staff { get; set; }
        public Nullable<int> fk_category { get; set; }
        public Nullable<System.DateTime> date_in { get; set; }
    
        public virtual category category { get; set; }
        public virtual staff staff { get; set; }
    }
}
